// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: rocket.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Rocket struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rocket) Reset() {
	*x = Rocket{}
	mi := &file_rocket_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rocket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rocket) ProtoMessage() {}

func (x *Rocket) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rocket.ProtoReflect.Descriptor instead.
func (*Rocket) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{0}
}

func (x *Rocket) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rocket) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Rocket) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// -- Get Rocket Request Types --
type GetRocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRocketRequest) Reset() {
	*x = GetRocketRequest{}
	mi := &file_rocket_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketRequest) ProtoMessage() {}

func (x *GetRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketRequest.ProtoReflect.Descriptor instead.
func (*GetRocketRequest) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{1}
}

func (x *GetRocketRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rocket        *Rocket                `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRocketResponse) Reset() {
	*x = GetRocketResponse{}
	mi := &file_rocket_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRocketResponse) ProtoMessage() {}

func (x *GetRocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRocketResponse.ProtoReflect.Descriptor instead.
func (*GetRocketResponse) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{2}
}

func (x *GetRocketResponse) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

// -- Add Rocket Message Types --
type AddRocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rocket        *Rocket                `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRocketRequest) Reset() {
	*x = AddRocketRequest{}
	mi := &file_rocket_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRocketRequest) ProtoMessage() {}

func (x *AddRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRocketRequest.ProtoReflect.Descriptor instead.
func (*AddRocketRequest) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{3}
}

func (x *AddRocketRequest) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type AddRocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rocket        *Rocket                `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRocketResponse) Reset() {
	*x = AddRocketResponse{}
	mi := &file_rocket_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRocketResponse) ProtoMessage() {}

func (x *AddRocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRocketResponse.ProtoReflect.Descriptor instead.
func (*AddRocketResponse) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{4}
}

func (x *AddRocketResponse) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

// -- Delete Rocket Message Types --
type DeleteRocketRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rocket        *Rocket                `protobuf:"bytes,1,opt,name=rocket,proto3" json:"rocket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRocketRequest) Reset() {
	*x = DeleteRocketRequest{}
	mi := &file_rocket_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRocketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRocketRequest) ProtoMessage() {}

func (x *DeleteRocketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRocketRequest.ProtoReflect.Descriptor instead.
func (*DeleteRocketRequest) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteRocketRequest) GetRocket() *Rocket {
	if x != nil {
		return x.Rocket
	}
	return nil
}

type DeleteRocketResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRocketResponse) Reset() {
	*x = DeleteRocketResponse{}
	mi := &file_rocket_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRocketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRocketResponse) ProtoMessage() {}

func (x *DeleteRocketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rocket_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRocketResponse.ProtoReflect.Descriptor instead.
func (*DeleteRocketResponse) Descriptor() ([]byte, []int) {
	return file_rocket_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRocketResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_rocket_proto protoreflect.FileDescriptor

const file_rocket_proto_rawDesc = "" +
	"\n" +
	"\frocket.proto\x12\trocket.v1\"@\n" +
	"\x06Rocket\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\"\n" +
	"\x10GetRocketRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\">\n" +
	"\x11GetRocketResponse\x12)\n" +
	"\x06rocket\x18\x01 \x01(\v2\x11.rocket.v1.RocketR\x06rocket\"=\n" +
	"\x10AddRocketRequest\x12)\n" +
	"\x06rocket\x18\x01 \x01(\v2\x11.rocket.v1.RocketR\x06rocket\">\n" +
	"\x11AddRocketResponse\x12)\n" +
	"\x06rocket\x18\x01 \x01(\v2\x11.rocket.v1.RocketR\x06rocket\"@\n" +
	"\x13DeleteRocketRequest\x12)\n" +
	"\x06rocket\x18\x01 \x01(\v2\x11.rocket.v1.RocketR\x06rocket\".\n" +
	"\x14DeleteRocketResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf0\x01\n" +
	"\rRocketService\x12F\n" +
	"\tGetRocket\x12\x1b.rocket.v1.GetRocketRequest\x1a\x1c.rocket.v1.GetRocketResponse\x12F\n" +
	"\tAddRocket\x12\x1b.rocket.v1.AddRocketRequest\x1a\x1c.rocket.v1.AddRocketResponse\x12O\n" +
	"\fDeleteRocket\x12\x1e.rocket.v1.DeleteRocketRequest\x1a\x1f.rocket.v1.DeleteRocketResponseB-Z+github.com/X-ecute/go-grpc/protos/rocket/v1b\x06proto3"

var (
	file_rocket_proto_rawDescOnce sync.Once
	file_rocket_proto_rawDescData []byte
)

func file_rocket_proto_rawDescGZIP() []byte {
	file_rocket_proto_rawDescOnce.Do(func() {
		file_rocket_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rocket_proto_rawDesc), len(file_rocket_proto_rawDesc)))
	})
	return file_rocket_proto_rawDescData
}

var file_rocket_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_rocket_proto_goTypes = []any{
	(*Rocket)(nil),               // 0: rocket.v1.Rocket
	(*GetRocketRequest)(nil),     // 1: rocket.v1.GetRocketRequest
	(*GetRocketResponse)(nil),    // 2: rocket.v1.GetRocketResponse
	(*AddRocketRequest)(nil),     // 3: rocket.v1.AddRocketRequest
	(*AddRocketResponse)(nil),    // 4: rocket.v1.AddRocketResponse
	(*DeleteRocketRequest)(nil),  // 5: rocket.v1.DeleteRocketRequest
	(*DeleteRocketResponse)(nil), // 6: rocket.v1.DeleteRocketResponse
}
var file_rocket_proto_depIdxs = []int32{
	0, // 0: rocket.v1.GetRocketResponse.rocket:type_name -> rocket.v1.Rocket
	0, // 1: rocket.v1.AddRocketRequest.rocket:type_name -> rocket.v1.Rocket
	0, // 2: rocket.v1.AddRocketResponse.rocket:type_name -> rocket.v1.Rocket
	0, // 3: rocket.v1.DeleteRocketRequest.rocket:type_name -> rocket.v1.Rocket
	1, // 4: rocket.v1.RocketService.GetRocket:input_type -> rocket.v1.GetRocketRequest
	3, // 5: rocket.v1.RocketService.AddRocket:input_type -> rocket.v1.AddRocketRequest
	5, // 6: rocket.v1.RocketService.DeleteRocket:input_type -> rocket.v1.DeleteRocketRequest
	2, // 7: rocket.v1.RocketService.GetRocket:output_type -> rocket.v1.GetRocketResponse
	4, // 8: rocket.v1.RocketService.AddRocket:output_type -> rocket.v1.AddRocketResponse
	6, // 9: rocket.v1.RocketService.DeleteRocket:output_type -> rocket.v1.DeleteRocketResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_rocket_proto_init() }
func file_rocket_proto_init() {
	if File_rocket_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rocket_proto_rawDesc), len(file_rocket_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rocket_proto_goTypes,
		DependencyIndexes: file_rocket_proto_depIdxs,
		MessageInfos:      file_rocket_proto_msgTypes,
	}.Build()
	File_rocket_proto = out.File
	file_rocket_proto_goTypes = nil
	file_rocket_proto_depIdxs = nil
}
